services:
  postgres:
    image: postgres:latest
    container_name: postgres-dynamis
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      postgres_network:
        ipv4_address: ${POSTGRES_IP}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

# IPAM -> IP Address Management
networks:
  postgres_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24 # Rango de direcciones
          gateway: 192.168.1.1 # La puerta de enlace para esta subred

volumes:
  pgdata: